# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'counter.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(344, 430)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NUM_1 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_1.setGeometry(QtCore.QRect(20, 100, 61, 61))
        self.NUM_1.setObjectName("NUM_1")
        self.NUM_2 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_2.setGeometry(QtCore.QRect(100, 100, 61, 61))
        self.NUM_2.setObjectName("NUM_2")
        self.NUM_7 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_7.setGeometry(QtCore.QRect(20, 240, 61, 61))
        self.NUM_7.setObjectName("NUM_7")
        self.NUM_8 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_8.setGeometry(QtCore.QRect(100, 240, 61, 61))
        self.NUM_8.setObjectName("NUM_8")
        self.NUM_9 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_9.setGeometry(QtCore.QRect(180, 240, 61, 61))
        self.NUM_9.setObjectName("NUM_9")
        self.NUM_4 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_4.setGeometry(QtCore.QRect(20, 170, 61, 61))
        self.NUM_4.setObjectName("NUM_4")
        self.NUM_5 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_5.setGeometry(QtCore.QRect(100, 170, 61, 61))
        self.NUM_5.setObjectName("NUM_5")
        self.NUM_6 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_6.setGeometry(QtCore.QRect(180, 170, 61, 61))
        self.NUM_6.setObjectName("NUM_6")
        self.subnum = QtWidgets.QPushButton(self.centralwidget)
        self.subnum.setGeometry(QtCore.QRect(270, 130, 61, 31))
        self.subnum.setObjectName("subnum")
        self.addnum = QtWidgets.QPushButton(self.centralwidget)
        self.addnum.setGeometry(QtCore.QRect(270, 90, 61, 31))
        self.addnum.setObjectName("addnum")
        self.mulnum = QtWidgets.QPushButton(self.centralwidget)
        self.mulnum.setGeometry(QtCore.QRect(270, 170, 61, 31))
        self.mulnum.setObjectName("mulnum")
        self.clean_num = QtWidgets.QPushButton(self.centralwidget)
        self.clean_num.setGeometry(QtCore.QRect(270, 250, 61, 61))
        self.clean_num.setObjectName("clean_num")
        self.snum = QtWidgets.QPushButton(self.centralwidget)
        self.snum.setGeometry(QtCore.QRect(270, 210, 61, 31))
        self.snum.setObjectName("snum")
        self.equals = QtWidgets.QLabel(self.centralwidget)
        self.equals.setGeometry(QtCore.QRect(10, 30, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.equals.setFont(font)
        self.equals.setObjectName("equals")
        self.NUM_3 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_3.setGeometry(QtCore.QRect(180, 100, 61, 61))
        self.NUM_3.setObjectName("NUM_3")
        self.NUM_0 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_0.setGeometry(QtCore.QRect(100, 310, 61, 61))
        self.NUM_0.setObjectName("NUM_0")
        self.NUM_10 = QtWidgets.QPushButton(self.centralwidget)
        self.NUM_10.setGeometry(QtCore.QRect(180, 310, 61, 61))
        self.NUM_10.setObjectName("NUM_10")
        self.dot = QtWidgets.QPushButton(self.centralwidget)
        self.dot.setGeometry(QtCore.QRect(20, 310, 61, 61))
        self.dot.setObjectName("dot")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(40, 20, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(60)
        self.result.setFont(font)
        self.result.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.result.setText("")
        self.result.setTextFormat(QtCore.Qt.AutoText)
        self.result.setObjectName("result")
        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(270, 320, 61, 31))
        self.equal.setObjectName("equal")
        self.symbol = QtWidgets.QLabel(self.centralwidget)
        self.symbol.setGeometry(QtCore.QRect(10, 10, 54, 21))
        self.symbol.setText("")
        self.symbol.setObjectName("symbol")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 20, 291))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(240, 90, 20, 291))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 80, 241, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(10, 370, 241, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 380, 121, 31))
        font = QtGui.QFont()
        font.setFamily("新蒂黑板报底字")
        font.setPointSize(11)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Counter -- By TTowFive"))
        self.NUM_1.setText(_translate("MainWindow", "1"))
        self.NUM_2.setText(_translate("MainWindow", "2"))
        self.NUM_7.setText(_translate("MainWindow", "7"))
        self.NUM_8.setText(_translate("MainWindow", "8"))
        self.NUM_9.setText(_translate("MainWindow", "9"))
        self.NUM_4.setText(_translate("MainWindow", "4"))
        self.NUM_5.setText(_translate("MainWindow", "5"))
        self.NUM_6.setText(_translate("MainWindow", "6"))
        self.subnum.setText(_translate("MainWindow", "-"))
        self.addnum.setText(_translate("MainWindow", "+"))
        self.mulnum.setText(_translate("MainWindow", "X"))
        self.clean_num.setText(_translate("MainWindow", "C"))
        self.snum.setText(_translate("MainWindow", "/"))
        self.equals.setText(_translate("MainWindow", "="))
        self.NUM_3.setText(_translate("MainWindow", "3"))
        self.NUM_0.setText(_translate("MainWindow", "0"))
        self.NUM_10.setText(_translate("MainWindow", "#"))
        self.dot.setText(_translate("MainWindow", "."))
        self.equal.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "<A href = \'https://github.com/TTowFive/Counter\'>关于本计算器</a>"))

